# Generated by Django 2.2 on 2020-01-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mark',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='accounts.Mark', verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
    ]
