# Generated by Django 2.2 on 2020-01-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200131_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mark',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='accounts.Mark', verbose_name='Модель'),
        ),
    ]
